sudo: required
services:
        - docker
before_install:
        - openssl aes-256-cbc -K $encrypted_c15510ef772d_key -iv $encrypted_c15510ef772d_iv -in multi-k8s-283923-96e63aee9a1f.json.enc -out multi-k8s-283923-96e63aee9a1f.json -d
        - export CLOUDSDK_CORE_DISABLE_PROMPTS=1
        - curl https://sdk.cloud.google.com | bash > /dev/null;
        - source $HOME/google-cloud-sdk/path.bash.inc
        - gcloud components update kubectl
        - gcloud auth active-service-account --key-file service-account.json
        - gcloud config set multi-k8s-283923
        - gcloud config set compute/zone southamerica-east1-a
        - gcloud container clusters get-credentials multi-cluster
        - echo $DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
